### ISSUE TITLE
gutenberg block code compiled successfully but does not open in browser

### ISSUE THREAD

**Issue by ganeshpataiya** [SofiaSousa/g-hello-world#1]
Hi Sofia,
I have followed all the steps which suggested to you.  "npm start"  
Gutenberg block code compiled successfully but does not open in the browser. I am using windows10.  Is this only work in Linux OS?

please check below-compiled code after run npm start:- 
PS F:\project\hello-world> npm start

> hello-world@1.0.0 start F:\project\hello-world
> npm run build && SET BLOCK_DIR=$PWD npm --prefix node_modules/@frontkom/g-editor start

> hello-world@1.0.0 build F:\project\hello-world
> SET NODE_ENV=production webpack

PS F:\project\hello-world>

**Comment by SofiaSousa** [comment]
Hi @pataiyaganesh25,

Honestly, I've never tried Gutenberg blocks in Windows :)

What kind of errors/warnings is reported in the console?

**Comment by ganeshpataiya** [comment]
Thanks @SofiaSous,
The issue has been fixed now the Gutenberg blocks working in the window for me.

I need help into the media video insert in the background of the cloud block. Could you please assist me how can I do this.

if you have any reference code for this So it's really helpful for me. Thanks in advance

**Comment by SofiaSousa** [comment]
I'm glad you fixed the problem, @pataiyaganesh25

Did you already check core blocks code in the WordPress/gutenberg repo? https://github.com/WordPress/gutenberg/tree/master/packages/block-library/src 

I think it could be useful for you.

**Comment by ganeshpataiya** [comment]
Thank you so much @SofiaSousa 
I haven't check it, let me check and try it :)

**Comment by ganeshpataiya** [comment]
thanks for help
